FROM node:alpine

WORKDIR /root/app

ENV MAILME_PORT=""
ENV MAILME_SMPT_HOST=""
ENV MAILME_SMPT_PORT=""
ENV MAILME_SMPT_USER=""
ENV MAILME_SMPT_PASS=""
ENV MAILME_SMPT_SSL=""
ENV MAILME_TO=""
ENV MAILME_RATE_LIMIT_MINS=""
ENV MAILME_RATE_LIMIT_REQUESTS=""

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE $MAILME_PORT

CMD ["node", "./bin/www"]